### ISSUE TITLE
AE2WTLib-11.6.3 and Applied botanics

### ISSUE THREAD

**Issue by fahdanwar** [alterNERDtive/VaultHunters-tweaks#1]
Hi,

I have noted a couple of things and it's fix. AE2WTLib-11.6.3 is no more supplied with U9 . i have a fresh U9 and needed to install it . Another thing i noted that you need at least Applied Botanics 1.0.3 version to make it work. It's confirmed that in u9 1.0.1 version don't work on one of my new installation. Both of these needed documentation changes only i think.

**Comment by alterNERDtive** [comment]
AE2WTLib never came with the pack :)

And yes, you need Applied Botanics 1.0.3. I don’t think I’m mentioning a version of that anywhere? If in doubt, use the latest.
